"""trades

Revision ID: 8aa401164613
Revises: d7336971272c
Create Date: 2026-06-30 16:30:18.880102
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa401164613'
down_revision: Union[str, None] = 'd7336971272c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.Enum('long', 'short', name='tradedirection', native_enum=False, length=10), nullable=False),
    sa.Column('order_type', sa.Enum('market', 'limit', name='ordertype', native_enum=False, length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('account_size_at_entry', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('risk_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('per_unit_risk', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('position_size', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('risk_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('rr_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('capital_exposure', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', name='tradestatus', native_enum=False, length=10), nullable=False),
    sa.Column('rule_overridden', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('r_multiple', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('result', sa.Enum('win', 'loss', 'breakeven', name='traderesult', native_enum=False, length=10), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_user_created', 'trades', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_trades_user_status', 'trades', ['user_id', 'status'], unique=False)
    op.create_index('ix_trades_user_strategy', 'trades', ['user_id', 'strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_user_strategy', table_name='trades')
    op.drop_index('ix_trades_user_status', table_name='trades')
    op.drop_index('ix_trades_user_created', table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
