"""screenshots

Revision ID: b9c69876be71
Revises: efc2b893ff80
Create Date: 2026-06-30 22:45:18.352821
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c69876be71'
down_revision: Union[str, None] = 'efc2b893ff80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenshots',
    sa.Column('trade_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('slot', sa.Enum('entry_trade_tf', 'entry_higher_tf', 'exit_trade_tf', 'exit_higher_tf', name='screenshotslot', native_enum=False, length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', 'slot', name='uq_screenshot_trade_slot')
    )
    op.create_index(op.f('ix_screenshots_trade_id'), 'screenshots', ['trade_id'], unique=False)
    op.create_index(op.f('ix_screenshots_user_id'), 'screenshots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screenshots_user_id'), table_name='screenshots')
    op.drop_index(op.f('ix_screenshots_trade_id'), table_name='screenshots')
    op.drop_table('screenshots')
    # ### end Alembic commands ###
