"""ai_insights

Revision ID: d147c8faef8c
Revises: b9c69876be71
Create Date: 2026-06-30 23:08:13.497430
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd147c8faef8c'
down_revision: Union[str, None] = 'b9c69876be71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insights',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trade_id', sa.Uuid(), nullable=True),
    sa.Column('insight_type', sa.Enum('trade_summary', 'performance', 'similar_trade', 'strategy_review', 'coaching', name='aiinsighttype', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', 'insufficient', name='aiconfidence', native_enum=False), nullable=False),
    sa.Column('inputs_snapshot', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_trade_id'), 'ai_insights', ['trade_id'], unique=False)
    op.create_index(op.f('ix_ai_insights_user_id'), 'ai_insights', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_insights_user_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_trade_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    # ### end Alembic commands ###
