"""risk_rules

Revision ID: e71acace8103
Revises: 8aa401164613
Create Date: 2026-06-30 17:02:45.331948
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e71acace8103'
down_revision: Union[str, None] = '8aa401164613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_rules',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rule_type', sa.Enum('max_risk_per_trade', 'daily_loss_limit', 'weekly_loss_limit', 'consecutive_loss_limit', name='ruletype', native_enum=False, length=30), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('severity', sa.Enum('warning', 'block', name='ruleseverity', native_enum=False, length=10), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'rule_type', name='uq_rule_user_type')
    )
    op.create_index(op.f('ix_risk_rules_user_id'), 'risk_rules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_rules_user_id'), table_name='risk_rules')
    op.drop_table('risk_rules')
    # ### end Alembic commands ###
