"""market_contexts

Revision ID: efc2b893ff80
Revises: e71acace8103
Create Date: 2026-06-30 21:06:11.937297
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc2b893ff80'
down_revision: Union[str, None] = 'e71acace8103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_contexts',
    sa.Column('trade_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('atr', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('rsi', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('volume', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('trend', sa.Enum('uptrend', 'downtrend', 'sideways', 'unknown', name='markettrend', native_enum=False, length=12), nullable=False),
    sa.Column('session', sa.Enum('asia', 'london', 'newyork', 'unknown', name='marketsession', native_enum=False, length=12), nullable=False),
    sa.Column('volatility_regime', sa.Enum('low', 'normal', 'high', 'unknown', name='volatilityregime', native_enum=False, length=12), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('higher_timeframe', sa.String(length=10), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_source', sa.Enum('stub', 'provider', 'manual', name='marketdatasource', native_enum=False, length=12), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_index(op.f('ix_market_contexts_user_id'), 'market_contexts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_contexts_user_id'), table_name='market_contexts')
    op.drop_table('market_contexts')
    # ### end Alembic commands ###
